### ISSUE TITLE
Error when homeassistant starts up

### ISSUE THREAD

**Issue by RubenDijk** [Kalivos/ha_openmediavault#5]
Home assistant version: 0.104.3
Openmediavault version: 5.2.7.1

Ha config:

```
- platform: openmediavault
  host: http://192.168.178.5:9090
  password: xxxxxx
  monitored_conditions:
    - hostname
    - version
    - processor
    - kernel
    - system_time
    - uptime
    - load_average
    - cpu_usage
    - memory_usage
```
2020-02-04 13:45:20 WARNING (MainThread) [custom_components.openmediavault.sensor] Unable to fetch data from openmediavault
2020-02-04 13:45:20 ERROR (MainThread) [homeassistant.components.sensor] openmediavault: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 299, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/openmediavault/sensor.py", line 145, in async_update
    self._api.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/openmediavault/sensor.py", line 247, in update
    self.get_system_information()
  File "/config/custom_components/openmediavault/sensor.py", line 226, in get_system_information
    if error_check['retry']:
UnboundLocalError: local variable 'error_check' referenced before assignment
